### PR TITLE
Gitlab fixes

### LINKED ISSUE #217: Add GitLab support
We are probably going to migrate to GitLab in the short/mid-term, so we need to prepare `neptune` to work with both GitHub and GitLab to support a smooth migration.

**Requirements**

- We will need to support both self-hosted GitLab instances and gitlab.com (and probably both OSS and Enterprise versions, if there are any differences.
- Priority number one is to be able to use `neptune-release` to make releases with GitLab projects (without losing the ability to do GitHub releases, which one to use should be auto-discovered from the clone URL for example, but should be overrideable just in case we need to work with remotes from both GH and GL on the same local repo).
- We need to be able to mix GitHub and GitLab projects in the overview and other tools that work with many projects at the same time.

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
closes #217

### CODE REVIEW

**Comment by mathias-baumann-sociomantic** [comment]
Fixed failing CI

**Comment by leandro-lucarella-sociomantic** [comment]
ping @mihails-strasuns

**Comment by mihails-strasuns** [comment]
Sorry for delay. This branch seems to work just fine (deduces version, generates notes, creates tag) until the very point of release creation. At which point it is stuck with 403:

```
Would you like to release those tags now? y/n: y
success
failed: Expected status code 2xx, got 403

HTTP/1.1 403 Forbidden
```

I have a token with `api`  permission and judging by http request logs (`-v`) it is being sent.

**Comment by mihails-strasuns** [comment]
I will still merge this as it fixes problems it is intended to fix.

**Pull request merged**
