### PR TITLE
Improve neptune overview report

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Enhances both information provided by report and its visual representation

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic AFAIR you have been asking for sha bit some time ago

**Comment by mathias-lang-sociomantic** [comment]
Yes, that would fix https://github.com/sociomantic-tsunami/neptune/issues/26

**Comment by mihails-strasuns-sociomantic** [comment]
- Added "fixes" line

**Comment by leandro-lucarella-sociomantic** [comment]
I gave it a quick look and didn't see anything wrong about it, but I will leave to @mathias-baumann-sociomantic now that he is more involved with the project.

**Pull request merged**
