### PR TITLE
Allow using https in upstream URL

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
I'm not sure if this is the best fix for this, but it's something.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
I'd rather replace check with proper regex https://github.com/sociomantic-tsunami/neptune/blob/master/src/overview/repository.d#L141-L142

**Comment by mathias-baumann-sociomantic** [comment]
I am not a fan of using regex too much but this simple check also seems too simple for my taste

**Comment by leandro-lucarella-sociomantic** [comment]
> I am not a fan of using regex too much but this simple check also seems too simple for my taste

What do you suggest then? If both the `overview` and `release` tools are using a check for what is a GitHub URL, maybe it should be moved to a common module? Maybe even octod?

**Comment by mathias-baumann-sociomantic** [comment]
I would favour something like this maybe:

```
                      .filter!(a=>a.canFind("git@github.com:" ~ upstream) ||
                                  a.canFind("https://github.com/" ~ upstream))
```

**Comment by mihails-strasuns-sociomantic** [comment]
And I am a big fan of using regex in cases they are designed for and very opposed to implementing ad-hoc inferior version of same check with manual conditions. If something has a strict pattern one can express without full blown grammar, regex is a natural tool that should be used for it. It ends up being both more reliable (i.e. no false positives/negatives) and more readable (no need to combine all conditions mentally to see if they indeed match the pattern).

**Comment by mathias-baumann-sociomantic** [comment]
I don't like it that much because it's like embedding another language into a language. Checking a complex regex for validity seems also way more difficult to me as they are generally pretty cumbersome to read. It is very easy to miss something or get it wrong with it.

**Comment by leandro-lucarella-sociomantic** [comment]
I think in this case I agree with @mathias-baumann-sociomantic, the regex you linked looks much more complicated to follow and understand than a simple find, and I don't think it is less reliable, as your regex will also match stuff like `https://git@github.com:org/repo` and will not match `https://AUTH_TOKEN@github.com/org/repo.git`, so I don't think it's is really more reliable in itself (if you capture different parts and then do extra verifications, it might be more reliable, but that case already looks quite complex and I think by just using what @mathias-baumann-sociomantic suggested we are at a very decent level of reliability and it's super clear).

PS: I do use regexes quite often, but again, I think in this case to do it proper, it will take quite some effort (we need to capture full URL schemas, then parse each part and depending on which schema it is, look at the parts differently to do the actual validation).

**Comment by leandro-lucarella-sociomantic** [comment]
Well, actually what @mathias-baumann-sociomantic suggested will also fail with an URL like: `https://user@github.com/org/repo`, which people might be using, somewhere. So actually I think my original version is more reliable in terms of accepting more valid cases (which I think is more important than reducing false positives).

This is why in the git-hub tool I decide to let the user configure what is the name of the remote upstream instead of guessing. Is a one-time configuration thing and it avoids all sorts of problems like this one...

**Comment by leandro-lucarella-sociomantic** [comment]
What we could do is what you did with the upstream, guessing but asking the user for confirmation if the config is not present, and save the config the user confirmed via `git config neptune.upstreamRemote` or something. git-hub will add an `upstreamremote` config in v1.0.0 that could also be used, if found, as a guess.

**Comment by leandro-lucarella-sociomantic** [comment]
Would it be too bad to accept this temporary fix until a more robust solution can be found?

**Comment by mathias-baumann-sociomantic** [comment]
For me it'd be fine.

**Comment by mihails-strasuns-sociomantic** [comment]
> the regex you linked looks much more complicated to follow and understand than a simple find

That is because it does something completely different from a simple find. Regex replacement for current check would be literally `git@github\.com:|https:\/\/github\.com\/` which is definitely less error-prone than several manual conditions. And hand-crafted replacement for original regex would take more than a dozen lines of code.

My statement is simple - for ANY specifc pattern to check, regular expression solution is easier to read and more reliable and there simply can't be any excuse other than performance to prefer the manual approach.

Of course, after certain amount of complexity regex becomes unreadable mess - this is hard to argue. But at this point trying to degrade to simpler approach won't help either because you desired pattern is too complicated itself. Proper approach once you get there is to separate whole check into separate module/function and ensure extensive test coverage for it - at which point it doesn't matter how it is implemented internally.

**Comment by leandro-lucarella-sociomantic** [comment]
> My statement is simple - for ANY specifc pattern to check, regular expression solution is easier to read and more reliable

Again, no. Your expression there will discard the https version if a user is specified. I know it is easily fixable, but again, in this case, I don't see any clear benefits to use a regex, I think the current approach is as good and more readable. Is just an heuristic. If you really think this is completely unacceptable, I will switch to a regex, but I really don't see it as a superior solution in this case.

**Comment by mihails-strasuns-sociomantic** [comment]
> Again, no. Your expression there will discard the https version if a user is specified.

Why you keep comparing some totally different regex written for a different purpose?

This is literally the code I would expect to see instead of the current one if one wants intentionally simple check:

```D
    bool contains ( string input, string pattern )
    {
        return !input.matchFirst(regex(pattern)).empty;
    }

    auto remotes = cmd("git remote -v")
                      .splitter!(a=>a == '\n')
                      .uniq()
                      .filter!(a=> a.contains(r"git@github\.com:|https:\/\/github\.com\/"))
```

Seeing as this is a recurring task, I personally think that writing precise submodule URL schema parser with own test suite is a good idea - but it is out of scope of this PR.

**Comment by leandro-lucarella-sociomantic** [comment]
> Why you keep comparing some totally different regex written for a different purpose?

I am not.


> "git@github\.com:|https:\/\/github\.com\/"

This is not correct, it will not consider an URL like `https://token@gitub.com/`... Do you really want to get into parsing the full user/pass, considering URL encoding, etc.?

**Comment by leandro-lucarella-sociomantic** [comment]
Again, I think it makes sense to give ultimate control to the user to chose what the remote for upstream is named locally, so this should be just a simple guess in case the user is too lazy. But being super smart at guessing and making guessing the only is the wrong approach IMHO.

**Comment by mihails-strasuns-sociomantic** [comment]
Are you even serious at this point?

> Do you really want to get into parsing the full user/pass, considering URL encoding, etc.?

I DONT GIVE A DAMN WHAT IS THE PATTERN AS LONG AS IT IS NOT BUNCH OF `IF` CHECKS

**Comment by leandro-lucarella-sociomantic** [comment]
OK, I'm too tired, if that's all you want, a regex, then you'll have it. But to fix this proper we actually need #87 IMHO.

Updated.

**Comment by leandro-lucarella-sociomantic** [comment]
So? Merge please?

**Comment by mihails-strasuns-sociomantic** [comment]
Am I supposed to see regex here? :)

**Comment by leandro-lucarella-sociomantic** [comment]
I don't know where it went... `git reflog` to the rescue, I hope...

**Comment by leandro-lucarella-sociomantic** [comment]
I took some time but I found it! :)

**Pull request merged**
