### PR TITLE
First v0 version should be v0.1.0

### LINKED ISSUE #134: neptune-release cannot properly handle first releases (for v0.x.x?)
The use-case: preparing the first release of a new library.  The default branch is `v0.x.x`.

When trying to prepare a first release using `neptune-release` (which I would expect to be tagged as `v0.1.0`), I get the following output:

```
We are on branch v0.x.x
Warning: No previous releases found. This should only be the case for your very first release!
Detected release <invalid>
Warning: No corresponding milestone found for <invalid>
Actions to be done:
 * Creating annotated tag <invalid> (git tag -F- <invalid> v0.x.x)
 * Create tracking branch v0.0.x (git branch v0.0.x <invalid>)
 * Create next major branch v1.x.x (git branch v1.x.x)
 * Checkout next major branch v1.x.x (git checkout v1.x.x)
 * Removing release notes (...)
 * Commiting removal of release notes (git commit -m Clear release notes after release)
 * Checkout original branch v0.x.x (git checkout v0.x.x)

Would you like to continue? y/n: n
```

If `neptune-release` is invoked with the `--pre-release` flag, things fare a little better but the inferred tag is clearly problematic:

```
We are on branch v0.x.x
Warning: No previous releases found. This should only be the case for your very first release!
Detected release v0.0.0-rc1
Warning: No corresponding milestone found for v0.0.0-rc1
Actions to be done:
 * Creating annotated tag v0.0.0-rc1 (git tag -F- v0.0.0-rc1 v0.x.x)
 * Checkout original branch v0.x.x (git checkout v0.x.x)
```

It's not clear (since I've never had cause to use it in other circumstances) whether there is a general problem of support for first releases, or whether it's support for a `v0.x.x` first release specifically that is missing (probably because it has not been attempted until now).

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
Fixes #134

### CODE REVIEW

**Comment by mathias-baumann-sociomantic** [comment]
Really? For that?!

**Comment by leandro-lucarella-sociomantic** [comment]
Ideally tests should be for everything. If writing a test for this is too time consuming, then I guess is OK to omit it, being such a corner case. But the general answer for your questions is...

TEST ALL THINGS!

**Comment by mathias-baumann-sociomantic** [comment]
I estimate at least 1h to write a test.

**Comment by mathias-baumann-sociomantic** [comment]
(for a change that took 1 minute)

**Comment by leandro-lucarella-sociomantic** [comment]
Can't you just write a unit test as opposed to a full blown integration test? Something seems wrong with the test infrastructure if the only way to test a 1minute change is to spend 1hour to write a test.

**Comment by mathias-baumann-sociomantic** [comment]
Added test

**Comment by mathias-baumann-sociomantic** [comment]
And mind you, the time it took to make a change (or the amount of lines changed) is absolutely no indicator to the effects of that change.

**Comment by leandro-lucarella-sociomantic** [comment]
> And mind you, the time it took to make a change (or the amount of lines changed) is absolutely no indicator to the effects of that change.

OK, scratch " a 1minute change" :D

**Comment by leandro-lucarella-sociomantic** [comment]
> Added test

Was it a 1 hour integration test? I was serious about being able to write unit tests too. If you can't make a simple unit test for this it might be an indication the architecture needs some tuning to be able to isolate components a bit more, so you don't need to go thought the whole thing to test just one component.

**Comment by mathias-baumann-sociomantic** [comment]
I suppose it was 20 minutes or so

**Pull request merged**
