### PR TITLE
Fix README links

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Review by scott-gibson-sociomantic — CHANGES_REQUESTED** [review]
There's a code comment also referencing /master in 
https://github.com/sociomantic-tsunami/neptune/blob/70d5c2d8605a0c6fe92198f84a6875e378e50655/src/autopr/SubModsUpdate.d#L173

**Comment by gavin-norman-sociomantic** [comment]
>There's a code comment also referencing /master in

Not within the scope of this PR!! ;)

Ok, I'll have a look...

**Comment by gavin-norman-sociomantic** [comment]
Updated.

**Review by scott-gibson-sociomantic — APPROVED** [review]

**Comment by mathias-baumann-sociomantic** [comment]
Not so happy with this change. Instead relative links could have been used like 
```
[Neptune Library Release Announcements](doc/announcements.md)
```

Now we're gonna have to change this with every major version.

**Comment by gavin-norman-sociomantic** [comment]
You're right. Relative links would be much better. Unfortunately that didn't occur to me at the time.

**Pull request merged**
