### PR TITLE
Ignore pre-releases when detecting next release

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
Part of #94

Requires #95

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I'm trying neptune with a bunch of patches, but the closest is this PR.

I basically rebased this PR on top of current master and then applied too the `Colorize some output` patch.

Here is the tree (I'm using the HEAD branch, of course):
```
* 3d67ff4 (HEAD -> test) Colorize some output
* fdaac68 Ignore pre-releases when detecting next release
* a0e10ab Simplify assume_yes logic using global options
* 33cd083 Provide globally accessible options
* 12c00f0 Add integration test of scenario "first release"
* da319e9 Sort release note sections for determinism
* 2d15ccf Update to makd v2.0.1
* 6b3c2bd Update vibed to v0.7.32
* 9193442 Update octod to version that supports ports
* 39c44c2 Add "no-send-mail" options
* 603b316 Add option "base-url" for easier testing
* 887e754 Minor documentation fix
* f267960 Add "assume-yes" option
* a776fd7 (origin/master, origin/HEAD) Explicitly look for type 'object' when checking milestone issues
* 283e520 Explicitly use --no-ff for merges
| * 7344b13 (marenz/addcolor) Colorize some output
|/  
| * a8be344 (marenz/prelease) Ignore pre-releases when detecting next release
| * bb20d79 (marenz/tests) Simplify assume_yes logic using global options
| * 33c85eb Provide globally accessible options
| * 39108b9 Add integration test of scenario "first release"
| | * 8502079 (marenz/upstream-remote) Make remote upstream name configurable
| | * 73ec8e7 Simplify assume_yes logic using global options
| | * 657cadb Provide globally accessible options
| | * f5996cc Add integration test of scenario "first release"
| |/  
| * a544692 Sort release note sections for determinism
| * c2b136f Update to makd v2.0.1
| * 2af207b Update vibed to v0.7.32
| * 4b75e46 Update octod to version that supports ports
| * a2864e9 Add "no-send-mail" options
| * 10360fb Add option "base-url" for easier testing
| * 4611916 Minor documentation fix
| * 210035e Add "assume-yes" option
|/  
* f13cc90 Implement email sending using sendmail
```

This is what I get trying to release beaver v0.2.2:

```
Some milestones on github should be closed: ["v0.2.2"]
Would you like to close them now? y/n: y
Closing v0.2.2 (0 open issues) ... success
This is the announcement email:
-----
From: Leandro Lucarella <leandro.lucarella@sociomantic.com>
Subject: [PatchRelease] beaver v0.2.2

If your application is using a previous beaver v0.2.x release, it should be updated to use this new patch release as soon as possible. As this is a patch release, it contains only bugfixes; it is guaranteed not to contain new features or API changes and will not require you to change your code.

Issues fixed in this release:

v0.2.2
======

* gen-dockerfile: Fix docker repository and tag parsing #29
* editorconfig: Fix indent for Makefiles #27
* Mention wildcard support in the readme #26

http://github.com/sociomantic-tsunami/beaver/releases/tag/v0.2.2

-----
release.shellHelper.ExitCodeException@./src/release/shellHelper.d(55): Cmd Failed:  (status 1)
----------------
./src/release/shellHelper.d:55 immutable(char)[] release.shellHelper.cmd(immutable(char)[]) [0x7eb3b8]
./src/release/gitHelper.d:170 immutable(char)[] release.gitHelper.getConfig(immutable(char)[]) [0x830371]
/home/luca/devel/neptune/src/release/main.d:202 _Dmain [0x7ce5e2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x99da0f]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x99d937]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x99d9b4]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x99d937]
??:? _d_run_main [0x99d8a3]
??:? main [0x7da409]
??:? __libc_start_main [0x4a7f982f]
```

**Comment by leandro-lucarella-sociomantic** [comment]
I just got this again when releasing git-hub v0.11.2.

```
-----
release.shellHelper.ExitCodeException@./src/release/shellHelper.d(55): Cmd Failed:  (status 1)
----------------
./src/release/shellHelper.d:55 immutable(char)[] release.shellHelper.cmd(immutable(char)[]) [0x7eb3b8]
./src/release/gitHelper.d:170 immutable(char)[] release.gitHelper.getConfig(immutable(char)[]) [0x830371]
/home/luca/devel/neptune/src/release/main.d:202 _Dmain [0x7ce5e2]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x99da0f]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x99d937]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x99d9b4]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x99d937]
??:? _d_run_main [0x99d8a3]
??:? main [0x7da409]
??:? __libc_start_main [0xa3f1c82f]
```

**Comment by mathias-baumann-sociomantic** [comment]
It's missing the git config `neptune.mail-recipient`

**Comment by mathias-baumann-sociomantic** [comment]
Created https://github.com/sociomantic-tsunami/neptune/pull/105 for you

**Comment by leandro-lucarella-sociomantic** [comment]
Needs rebase now.

**Comment by mathias-baumann-sociomantic** [comment]
rebased

**Comment by mathias-baumann-sociomantic** [comment]
Rebased

**Comment by leandro-lucarella-sociomantic** [comment]
I will merge even when I don't have a test case anymore. Maybe neptune itself could be a test :D

**Pull request merged**
